# Generated by Django 5.2.3 on 2025-06-21 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('categoria', models.CharField(default='General', max_length=100)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('tipo', models.CharField(help_text='Ej: Bus, Camión, Camioneta', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('rut', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, unique=True)),
                ('horas_hombre', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('costo_base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, unique=True)),
                ('criticidad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=10)),
                ('causa', models.CharField(choices=[('MECANICA', 'Mecánica'), ('ELECTRICA', 'Eléctrica'), ('OPERACION', 'Operación')], default='MECANICA', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInsumoOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flota.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDeTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('FINALIZADA', 'Finalizada'), ('CERRADA_MECANICO', 'Cerrada por Mecánico')], default='PENDIENTE', max_length=20)),
                ('tipo', models.CharField(choices=[('PREVENTIVA', 'Preventiva'), ('CORRECTIVA', 'Correctiva')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('kilometraje_apertura', models.PositiveIntegerField()),
                ('kilometraje_cierre', models.PositiveIntegerField(blank=True, null=True)),
                ('observacion_inicial', models.TextField(blank=True, null=True)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('motivo_pendiente', models.TextField(blank=True, help_text='Motivo por el cual el mecánico deja la OT pendiente o cerrada para revisión.', null=True)),
                ('insumos_utilizados', models.ManyToManyField(blank=True, through='flota.DetalleInsumoOT', to='flota.insumo')),
                ('personal_asignado', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flota.proveedor')),
                ('tareas_realizadas', models.ManyToManyField(blank=True, to='flota.tarea')),
                ('tipo_falla', models.ForeignKey(blank=True, help_text='Solo para OTs correctivas', null=True, on_delete=django.db.models.deletion.SET_NULL, to='flota.tipofalla')),
            ],
        ),
        migrations.AddField(
            model_name='detalleinsumoot',
            name='orden_de_trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flota.ordendetrabajo'),
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('MECANICO', 'Mecánico'), ('ASISTENTE', 'Asistente')], default='MECANICO', max_length=20)),
                ('user', models.OneToOneField(blank=True, help_text='Usuario de Django asociado para el inicio de sesión.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PautaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('kilometraje_pauta', models.PositiveIntegerField()),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='pautas/')),
                ('modelo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pautas', to='flota.modelovehiculo')),
                ('tareas', models.ManyToManyField(blank=True, to='flota.tarea')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_interno', models.CharField(max_length=50, unique=True)),
                ('patente', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('kilometraje_actual', models.PositiveIntegerField(default=0)),
                ('chasis', models.CharField(blank=True, max_length=100, null=True)),
                ('motor', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_actualizacion_km', models.DateTimeField(auto_now=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='flota.modelovehiculo')),
            ],
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to='flota.vehiculo'),
        ),
        migrations.CreateModel(
            name='BitacoraDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horas_operativas', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('horas_mantenimiento_prog', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('horas_falla', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='flota.vehiculo')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('vehiculo', 'fecha')},
            },
        ),
    ]
