# Generated by Django 5.2.3 on 2025-06-21 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='tfs_minutos',
            field=models.PositiveIntegerField(default=0, help_text='Tiempo total en minutos que la unidad estuvo detenida por esta falla.', verbose_name='Tiempo Fuera de Servicio (minutos)'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Usuario de Django asociado para el inicio de sesión. Déjelo en blanco si no necesita login.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
