# Generated by Django 5.2.3 on 2025-06-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0002_ordendetrabajo_tfs_minutos_alter_personal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='formato',
            field=models.CharField(choices=[('NORMAL', 'Mantenimiento Normal'), ('CONTRATO', 'Bajo Contrato')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='aplicacion',
            field=models.CharField(blank=True, help_text='Ej: Faena, Carretera, Interurbano', max_length=100, null=True),
        ),
    ]
