# Generated by Django 5.2.3 on 2025-06-24 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0003_ordendetrabajo_formato_vehiculo_aplicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormaEuro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: EURO V, EURO VI', max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='pauta_mantenimiento',
            field=models.ForeignKey(blank=True, help_text='Pauta asociada, solo para OTs de tipo PREVENTIVA', null=True, on_delete=django.db.models.deletion.SET_NULL, to='flota.pautamantenimiento'),
        ),
        migrations.AddField(
            model_name='pautamantenimiento',
            name='intervalo_km',
            field=models.PositiveIntegerField(default=10000, help_text='Intervalo en kilómetros para esta pauta (ej. 10000, 20000)'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='norma_euro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='flota.normaeuro'),
        ),
    ]
