# Generated by Django 5.2.3 on 2025-06-24 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0004_normaeuro_ordendetrabajo_pauta_mantenimiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Mecánico principal a cargo de la OT.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ots_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='personal_asignado',
            field=models.ManyToManyField(blank=True, help_text='Equipo de ayudantes que participan en la OT.', related_name='ots_ayudante', to=settings.AUTH_USER_MODEL),
        ),
    ]
