# Generated by Django 5.2.3 on 2025-06-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0005_ordendetrabajo_responsable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_alerta_mantenimiento', models.PositiveIntegerField(default=25, help_text="Porcentaje del intervalo de KM para activar la alerta 'PRÓXIMO'. Ej: 25 para 25%.")),
            ],
            options={
                'verbose_name_plural': 'Configuraciones de Empresa',
            },
        ),
    ]
