# Generated by Django 5.2.3 on 2025-06-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0006_configuracionempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionempresa',
            name='porcentaje_alerta_mantenimiento',
            field=models.PositiveIntegerField(default=25, help_text="Porcentaje del intervalo de KM para activar la alerta 'PRÓXIMO'. Ej: 25."),
        ),
    ]
