# Generated by Django 5.2.3 on 2025-06-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0007_alter_configuracionempresa_porcentaje_alerta_mantenimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='diagnostico_evaluacion',
            field=models.TextField(blank=True, help_text='Conclusión técnica del mecánico tras la evaluación.'),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='motivo_pausa',
            field=models.CharField(blank=True, choices=[('FALTA_REPUESTO', 'Falta de Repuesto'), ('ESPERA_AUTORIZACION', 'Espera de Autorización'), ('FALTA_HERRAMIENTA', 'Falta de Herramienta Especial'), ('OTRO', 'Otro (ver notas)')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='notas_pausa',
            field=models.TextField(blank=True, help_text='Detalles adicionales sobre el motivo de la pausa.'),
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='sintomas_reportados',
            field=models.TextField(blank=True, help_text='Descripción de síntomas (ruidos, luces, etc.) reportados por el conductor.'),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('PAUSADA', 'Pausada'), ('FINALIZADA', 'Finalizada'), ('CERRADA_MECANICO', 'Cerrada por Mecánico')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='tipo',
            field=models.CharField(choices=[('PREVENTIVA', 'Preventiva'), ('CORRECTIVA', 'Correctiva'), ('EVALUATIVA', 'Evaluativa')], max_length=20),
        ),
    ]
