# Generated by Django 5.2.3 on 2025-06-29 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0008_ordendetrabajo_diagnostico_evaluacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('tipo_evento', models.CharField(choices=[('CREACION', 'Creación de OT'), ('ASIGNACION', 'Asignación de Personal'), ('INICIO', 'Inicio de Tareas'), ('PAUSA', 'OT Pausada'), ('REANUDACION', 'OT Reanudada'), ('CIERRE_MECANICO', 'Cierre por Mecánico'), ('FINALIZACION', 'Finalización de OT'), ('MODIFICACION', 'Modificación de Datos'), ('COMENTARIO', 'Comentario')], max_length=20)),
                ('descripcion', models.TextField(help_text="Detalle del evento. Ej: 'Pausada por falta de repuesto: Filtro de aceite.'")),
                ('orden_de_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='flota.ordendetrabajo')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_evento'],
            },
        ),
    ]
