# Generated by Django 5.2.3 on 2025-06-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0009_historialot'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='fecha_programada',
            field=models.DateField(blank=True, help_text='Fecha en la que se planea realizar la OT.', null=True),
        ),
    ]
