# Generated by Django 5.2.3 on 2025-06-30 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0010_ordendetrabajo_fecha_programada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='diagnostico_evaluacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('PAUSADA', 'Pausada'), ('CERRADA_MECANICO', 'Cerrada por Mecánico'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='fecha_programada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='folio',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='formato',
            field=models.CharField(choices=[('INTERNO', 'Interno'), ('EXTERNO', 'Externo')], default='INTERNO', max_length=10),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='kilometraje_apertura',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='motivo_pausa',
            field=models.CharField(blank=True, choices=[('FALTA_REPUESTO', 'Falta de Repuesto'), ('ESPERA_AUTORIZACION', 'Espera de Autorización'), ('FALTA_PERSONAL', 'Falta de Personal'), ('OTRO', 'Otro')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='motivo_pendiente',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='notas_pausa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='pauta_mantenimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flota.pautamantenimiento'),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='personal_asignado',
            field=models.ManyToManyField(blank=True, related_name='ots_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ots_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='sintomas_reportados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='tareas_realizadas',
            field=models.ManyToManyField(blank=True, related_name='ordenes_de_trabajo', to='flota.tarea'),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='tfs_minutos',
            field=models.PositiveIntegerField(default=0, help_text='Tiempo Fuera de Servicio en minutos'),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='tipo_falla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flota.tipofalla'),
        ),
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_de_trabajo', to='flota.vehiculo'),
        ),
    ]
