# Generated by Django 5.2.3 on 2025-06-30 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0011_ordendetrabajo_prioridad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del repuesto (ej: Filtro de Aceite Motor OM906)', max_length=255)),
                ('numero_parte', models.CharField(help_text='Número de parte o SKU del fabricante', max_length=100)),
                ('calidad', models.CharField(choices=[('ORIGINAL', 'Original'), ('OEM', 'Alternativo OEM'), ('GENERICO', 'Alternativo Genérico')], default='GENERICO', max_length=20)),
                ('stock_actual', models.PositiveIntegerField(default=0, verbose_name='Stock Actual')),
                ('stock_minimo', models.PositiveIntegerField(default=1, verbose_name='Stock Mínimo de Alerta')),
                ('ubicacion', models.CharField(blank=True, help_text='Ubicación en bodega (ej: Estante A, Casillero 3)', max_length=100, null=True)),
                ('proveedor_habitual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flota.proveedor')),
            ],
            options={
                'verbose_name': 'Repuesto',
                'verbose_name_plural': 'Repuestos',
                'unique_together': {('numero_parte', 'calidad')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada (Compra/Recepción)'), ('SALIDA_OT', 'Salida por OT'), ('AJUSTE_POSITIVO', 'Ajuste de Inventario (Suma)'), ('AJUSTE_NEGATIVO', 'Ajuste de Inventario (Resta)')], max_length=20)),
                ('cantidad', models.IntegerField(help_text='Cantidad del movimiento. Positivo para entradas/ajustes+, negativo para salidas/ajustes-.')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('orden_de_trabajo', models.ForeignKey(blank=True, help_text='OT asociada a la salida de stock', null=True, on_delete=django.db.models.deletion.SET_NULL, to='flota.ordendetrabajo')),
                ('usuario_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='flota.repuesto')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-fecha_movimiento'],
            },
        ),
    ]
