# Generated by Django 5.2.3 on 2025-06-30 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0012_repuesto_movimientostock'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepuestoRequeridoPorTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.PositiveIntegerField(default=1)),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flota.repuesto')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flota.tarea')),
            ],
            options={
                'unique_together': {('tarea', 'repuesto')},
            },
        ),
        migrations.AddField(
            model_name='tarea',
            name='repuestos_requeridos',
            field=models.ManyToManyField(blank=True, related_name='tareas_que_lo_requieren', through='flota.RepuestoRequeridoPorTarea', to='flota.repuesto'),
        ),
    ]
