# Generated by Django 5.2.3 on 2025-06-30 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0013_repuestorequeridoportarea_tarea_repuestos_requeridos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordendetrabajo',
            name='insumos_utilizados',
        ),
        migrations.AddField(
            model_name='detalleinsumoot',
            name='repuesto_inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_ot_asociados_consumo', to='flota.repuesto'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='detalleinsumoot',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flota.insumo'),
        ),
        migrations.AlterField(
            model_name='detalleinsumoot',
            name='orden_de_trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_insumos_ot', to='flota.ordendetrabajo'),
        ),
        migrations.AddConstraint(
            model_name='detalleinsumoot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('insumo__isnull', True), ('repuesto_inventario__isnull', False)), models.Q(('insumo__isnull', False), ('repuesto_inventario__isnull', True)), _connector='OR'), name='one_of_repuesto_or_insumo_not_both_v2'),
        ),
    ]
