# Generated by Django 5.2.3 on 2025-07-02 04:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0014_remove_ordendetrabajo_insumos_utilizados_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionAmbiental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_medicion', models.DateField()),
                ('temperatura_celsius', models.IntegerField(default=15)),
                ('condicion_climatica', models.CharField(choices=[('DESPEJADO', 'Despejado'), ('LLUVIA', 'Lluvia'), ('VIENTO', 'Viento Fuerte'), ('NIEVE', 'Nieve')], default='DESPEJADO', max_length=20)),
                ('nivel_trafico', models.CharField(choices=[('BAJO', 'Bajo'), ('MODERADO', 'Moderado'), ('ALTO', 'Alto')], default='BAJO', max_length=20)),
            ],
            options={
                'verbose_name': 'Condición Ambiental',
                'verbose_name_plural': 'Condiciones Ambientales',
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Calama - Antofagasta', max_length=255, unique=True)),
                ('distancia_km', models.DecimalField(decimal_places=2, help_text='Distancia estándar de la ruta en kilómetros', max_digits=10)),
                ('topografia', models.CharField(choices=[('PLANO', 'Plano'), ('MIXTO', 'Mixto'), ('MONTANOSO', 'Montañoso')], default='MIXTO', max_length=20)),
                ('tipo_pavimento', models.CharField(choices=[('ASFALTO', 'Asfalto'), ('TIERRA', 'Tierra'), ('MIXTO', 'Mixto')], default='ASFALTO', max_length=20)),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
            },
        ),
        migrations.CreateModel(
            name='CargaCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateTimeField(default=django.utils.timezone.now)),
                ('kilometraje_en_carga', models.PositiveIntegerField(help_text='Odómetro del vehículo al momento de la carga')),
                ('litros_cargados', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_por_litro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_total_carga', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('es_tanque_lleno', models.BooleanField(default=True, help_text='Marcar si la carga fue para llenar el tanque')),
                ('rendimiento_calculado_kml', models.DecimalField(blank=True, decimal_places=2, help_text='Calculado automáticamente al registrar la siguiente carga.', max_digits=6, null=True, verbose_name='Rendimiento del Tramo Anterior (Km/L)')),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_combustible', to='flota.vehiculo')),
                ('condicion_ambiental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flota.condicionambiental')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flota.ruta')),
            ],
            options={
                'verbose_name': 'Carga de Combustible',
                'verbose_name_plural': 'Cargas de Combustible',
                'ordering': ['-fecha_carga'],
            },
        ),
    ]
