# Generated by Django 5.2.3 on 2025-07-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0015_condicionambiental_ruta_cargacombustible'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Razón social o propietario del vehículo', max_length=255, null=True),
        ),
    ]
