# Generated by Django 5.2.3 on 2025-07-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0016_vehiculo_razon_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendetrabajo',
            name='horas_extra_autorizadas',
            field=models.BooleanField(default=False, help_text='Indica si un supervisor autorizó trabajar fuera del tiempo estándar o del horario laboral.'),
        ),
    ]
