# Generated by Django 5.2.3 on 2025-07-04 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0017_ordendetrabajo_horas_extra_autorizadas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(help_text="El texto que verá el usuario. Ej: 'La OT #123 fue pausada por Juan Pérez.'", max_length=255)),
                ('leida', models.BooleanField(default=False)),
                ('url_destino', models.CharField(blank=True, help_text='URL a la que se dirige la notificación. Ej: /ot/123/detail/', max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
