# Generated by Django 5.2.3 on 2025-07-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0018_notificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='horas_hombre',
        ),
        migrations.AddField(
            model_name='tarea',
            name='tiempo_estandar_minutos',
            field=models.PositiveIntegerField(default=60, help_text='Tiempo estándar para completar esta tarea, en minutos.'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='costo_base',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo base de mano de obra para esta tarea, sin incluir repuestos.', max_digits=10),
        ),
    ]
