# Generated by Django 5.2.3 on 2025-07-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0019_remove_tarea_horas_hombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionempresa',
            name='horas_laborales_mes_por_persona',
            field=models.PositiveIntegerField(default=160, help_text='Número de horas de trabajo estándar que una persona tiene disponibles en un mes. Se usa para calcular la capacidad del equipo.', verbose_name='Horas Laborales Base por Mes'),
        ),
    ]
