# Generated by Django 5.2.3 on 2025-07-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0020_configuracionempresa_horas_laborales_mes_por_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelovehiculo',
            name='rendimiento_optimo_kml',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text="Rendimiento en Km/L a partir del cual se considera 'ÓPTIMO' (verde).", max_digits=5, verbose_name='Rendimiento Óptimo (Km/L)'),
        ),
        migrations.AddField(
            model_name='modelovehiculo',
            name='rendimiento_regular_kml',
            field=models.DecimalField(decimal_places=2, default=4.0, help_text="Rendimiento en Km/L a partir del cual se considera 'REGULAR' (amarillo).", max_digits=5, verbose_name='Rendimiento Regular (Km/L)'),
        ),
    ]
