from django.urls import path
from . import views

app_name = 'flota'

urlpatterns = [
    path('', views.dashboard_flota, name='dashboard'),
    path('ordenes/crear/', views.orden_trabajo_create, name='ot_create'), # Added this line
    path('api/ot-eventos/', views.ot_eventos_api, name='ot_eventos_api'),
    path('inventario/', views.repuesto_list, name='repuesto_list'),
    path('inventario/nuevo/', views.repuesto_create, name='repuesto_create'),
    path('inventario/<int:pk>/', views.repuesto_detail, name='repuesto_detail'),
    path('inventario/<int:pk>/editar/', views.repuesto_update, name='repuesto_update'),
    path('inventario/<int:repuesto_pk>/registrar-movimiento/', views.registrar_movimiento, name='registrar_movimiento'),
    path('ordenes/', views.orden_trabajo_list, name='ot_list'),
    path('ordenes/<int:pk>/', views.orden_trabajo_detail, name='ot_detail'),
    path('ordenes/<int:pk>/cambiar-estado/', views.cambiar_estado_ot, name='cambiar_estado_ot'),
    path('ordenes/<int:pk>/pdf/', views.generar_ot_pdf, name='generar_ot_pdf'),
    path('pizarra-programacion/', views.pizarra_programacion, name='pizarra_programacion'),
    path('vehiculo/<int:pk>/actualizar-km/', views.actualizar_km_vehiculo, name='actualizar_km'),
    path('indicadores/', views.indicadores_dashboard, name='indicadores_dashboard'),
    path('analisis-fallas/', views.analisis_fallas, name='analisis_fallas'),
    path('analisis-avanzado/', views.analisis_avanzado, name='analisis_avanzado'),
    path('carga-masiva/', views.carga_masiva, name='carga_masiva'),
    path('vehiculo/<int:pk>/historial/', views.historial_vehiculo, name='historial_vehiculo'),
    path('vehiculo/<int:pk>/analisis-km/', views.analisis_km_vehiculo, name='analisis_km_vehiculo'),
    path('orden-trabajo/<int:ot_pk>/eliminar-tarea/<int:tarea_pk>/', views.eliminar_tarea_ot, name='eliminar_tarea_ot'),
    path('orden-trabajo/<int:ot_pk>/eliminar-insumo/<int:detalle_pk>/', views.eliminar_insumo_ot, name='eliminar_insumo_ot'),
    path('api/mecanicos-recursos/', views.mecanicos_recursos_api, name='mecanicos_recursos_api'),
    path('api/ot-actualizar-fecha/<int:pk>/', views.actualizar_fecha_ot_api, name='actualizar_fecha_ot_api'),
    path('api/repuestos/search/', views.repuesto_search_api, name='repuesto_search_api'),
    path('api/ots/add-repuesto/', views.add_repuesto_a_ot_api, name='add_repuesto_a_ot_api'),
    path('pizarra-combustible/', views.pizarra_combustible, name='pizarra_combustible'),
    path('combustible/registrar/', views.registrar_carga_combustible, name='registrar_carga_combustible'),
    path('ot/<int:pk>/autorizar-horas-extra/', views.autorizar_horas_extra, name='autorizar_horas_extra'),
    path('notificaciones/', views.lista_notificaciones, name='lista_notificaciones'),
    path('api/notificaciones/marcar-leidas/', views.marcar_notificaciones_leidas, name='marcar_notificaciones_leidas'),
    path('administracion/usuarios/', views.lista_usuarios, name='lista_usuarios'),
    path('administracion/usuarios/crear/', views.crear_usuario, name='crear_usuario'),
    path('administracion/usuarios/editar/<int:user_id>/', views.editar_usuario, name='editar_usuario'),
    path('kpi-rrhh/', views.kpi_rrhh_dashboard, name='kpi_rrhh_dashboard'),
    path('reportes/', views.reportes_dashboard, name='reportes_dashboard'),
    path('exportar/vehiculos-csv/', views.export_vehiculos_csv, name='export_vehiculos_csv'),
    path('exportar/repuestos-csv/', views.export_repuestos_csv, name='export_repuestos_csv'),
    path('exportar/ots-csv/', views.export_ots_csv, name='export_ots_csv'),
]
